export default function Head() {
  return (
    <>
      <title>Jawwad Khan | Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="/favicon/favicon.ico" sizes="any" />
    </>
  );
}
